export const portfolioData = {
  personal: {
    name: 'NGUYỄN MINH ANH',
    title: 'Internal Communications & Culture Specialist',
    tagline: 'Storyteller for organizational culture at scale',
    bio: 'Passionate about building culture that sticks. I craft authentic narratives for teams at scale, blend strategy with creativity, and thrive in tech environments. Athlete at heart, energy-driven, and always learning.',
    email: 'nguyenminhanh8688@gmail.com',
    phone: '0336 32 8088',
    location: 'Hanoi, Vietnam',
    portfolio: 'bit.ly/nguyenminhanhic',
  },
  
  stats: [
    { number: '5+', label: 'Years Experience' },
    { number: '600+', label: 'CBNV Reached' },
    { number: '30+', label: 'Projects Led' },
  ],

  caseStudies: [
    {
      id: 1,
      company: 'PHD Ltd.',
      logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
      title: 'Culture Foundation Launch',
      subtitle: 'Launching organizational values for retail scale-up',
      role: 'Lead, Internal Communications',
      timeline: '03/2024 – 07/2025',
      results: [
        '70% CBNV participation',
        '90% value comprehension',
        '10K+ engagements',
      ],
      description: 'Led a comprehensive culture campaign for a retail company scaling from 75 to 500+ stores. Designed master plan, produced multi-channel content, measured impact.',
      image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&fit=crop',
      color: 'from-blue-600 to-cyan-500',
    },
    {
      id: 2,
      company: 'CMC Global',
      logo: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=100&h=100&fit=crop',
      title: 'Tech Culture Through Music',
      subtitle: 'Creating authentic culture narrative for engineering team',
      role: 'Communications Lead to CSO',
      timeline: '10/2021 – 06/2022',
      results: [
        'Engineering team engagement',
        'Culture acceptance',
        'Tech-tone storytelling',
      ],
      description: 'Produced culture content for tech team - music video, tech talks, engagement programs. Bridged engineering and business mindsets.',
      image: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=800&fit=crop',
      color: 'from-purple-600 to-pink-500',
    },
    {
      id: 3,
      company: 'Everygolf Vietnam',
      logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
      title: 'Brand Foundation & Events',
      subtitle: 'Company positioning + flagship event production',
      role: 'Communications to Chairman',
      timeline: '06/2022 – 10/2023',
      results: [
        '41-page company profile',
        '150+ event participants',
        'Brand positioning clarity',
      ],
      description: 'Led 41-page bilingual company profile, organized 5+ major events including international speaker hosting, established brand narrative.',
      image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&fit=crop',
      color: 'from-green-600 to-emerald-500',
    },
    {
      id: 4,
      company: 'NIKE Vietnam',
      logo: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=100&h=100&fit=crop',
      title: 'Onboarding & Community',
      subtitle: 'New hire integration + internal engagement',
      role: 'Training Specialist',
      timeline: '08/2018 – 05/2021',
      results: [
        'System-wide onboarding',
        'Running Club community',
        'Leadership programs',
      ],
      description: 'Designed company-wide onboarding program, founded Running Club, organized leadership trainings and team building events.',
      image: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=800&fit=crop',
      color: 'from-orange-600 to-red-500',
    },
    {
      id: 5,
      company: 'FUNiX University',
      logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=100&h=100&fit=crop',
      title: 'Career Mentoring',
      subtitle: 'Guiding students in communications & HR',
      role: 'Mentor (Part-time)',
      timeline: '01/2026 – Present',
      results: [
        'Student guidance',
        'Career clarity',
        'Ongoing learning',
      ],
      description: 'Mentoring students in communications, HR, and career development. Staying connected to the talent development ecosystem.',
      image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&fit=crop',
      color: 'from-indigo-600 to-blue-500',
    },
  ],

  skills: [
    {
      group: 'Strategy & System',
      items: [
        'IC Framework & Master plan',
        'Stakeholder mapping',
        'Pulse Survey & eNPS',
        'Voice of Employee report',
        'Communications measurement',
      ],
    },
    {
      group: 'Content Production',
      items: [
        'Writing & Editing',
        'Visual: Canva, Photoshop',
        'Video: CapCut, Premiere',
        'AI tools: ChatGPT, Claude, Gemini',
        'Bilingual content (EN-VI)',
      ],
    },
    {
      group: 'Event & Engagement',
      items: [
        'Master plan & Timeline',
        'Vendor management',
        'MC / Hosting / Coordination',
        'Production direction',
      ],
    },
    {
      group: 'Soft Skills',
      items: [
        'Strategic communications',
        'Public speaking',
        'Cross-functional coordination',
        'Stakeholder management',
      ],
    },
  ],
}
